import { ArrowRight } from 'lucide-react'
import { motion } from 'motion/react'
import { Link } from 'react-router-dom'

import { projects, type Project } from '../../data/projects'
import { Container } from '../ui/container'

export function ProjectCaseStudy({ project }: { project: Project }) {
  const related = projects.filter((item) => item.sector === project.sector && item.id !== project.id).slice(0, 3)
  return <>
    <section className="relative isolate min-h-[82svh] overflow-hidden bg-ink text-white"><motion.img src={project.coverImage} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover" initial={{ opacity: 0, scale: 1.04 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.1 }} /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-black/85 via-black/30 to-black/25" /><Container className="flex min-h-[82svh] flex-col justify-end pb-12 pt-36 sm:pb-16 lg:pb-20"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.1 }}><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-white/70 uppercase">{project.category}</p><h1 className="mt-5 max-w-5xl font-display text-[clamp(4rem,9vw,9rem)] leading-[0.78] tracking-[-0.06em]">{project.title}</h1><dl className="mt-10 grid max-w-3xl grid-cols-2 gap-x-8 gap-y-5 border-t border-white/25 pt-5 text-sm sm:grid-cols-4">{[['Location', project.location], ['Area', project.area], ['Year', project.year], ['Category', project.category]].map(([label, value]) => <div key={label}><dt className="text-[0.58rem] font-semibold tracking-[0.16em] text-white/55 uppercase">{label}</dt><dd className="mt-1 leading-5 text-white/90">{value}</dd></div>)}</dl></motion.div></Container></section>
    <section className="bg-surface py-28 sm:py-36 lg:py-48"><Container className="grid gap-12 md:grid-cols-12"><motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.8 }} className="md:col-span-7"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Project story</p><h2 className="mt-6 font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl">Designed to become more familiar with every day.</h2></motion.div><p className="max-w-lg text-sm leading-8 text-muted md:col-span-4 md:col-start-9">{project.story}</p></Container></section>
    <section className="bg-canvas py-6 sm:py-10"><Container className="grid gap-6 md:grid-cols-12">{project.gallery.map((image, index) => <motion.div key={`${image}-${index}`} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.8 }} className={index === 0 ? 'aspect-[4/5] overflow-hidden md:col-span-7' : 'aspect-[4/5] overflow-hidden md:col-span-5'}><img src={image} alt={`${project.title} interior detail`} className="h-full w-full object-cover" /></motion.div>)}</Container></section>
    <section className="bg-canvas py-28 sm:py-36 lg:py-48"><Container className="grid gap-16 lg:grid-cols-2 lg:gap-28"><div><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Design highlights</p><ul className="mt-8 border-t border-line">{project.highlights.map((item, index) => <li key={item} className="flex gap-5 border-b border-line py-6"><span className="text-[0.62rem] font-semibold tracking-[0.16em] text-accent">0{index + 1}</span><span className="font-display text-2xl leading-[1.05] tracking-[-0.025em]">{item}</span></li>)}</ul></div><div><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Materials used</p><div className="mt-8 flex flex-wrap gap-3">{project.materials.map((material) => <span key={material} className="border border-line px-4 py-3 text-[0.64rem] font-semibold tracking-[0.14em] text-muted uppercase">{material}</span>)}</div><div className="mt-16 border-t border-line pt-8"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">The challenge</p><p className="mt-4 text-sm leading-8 text-muted">{project.challenge}</p></div><div className="mt-12 border-t border-line pt-8"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Final outcome</p><p className="mt-4 text-sm leading-8 text-muted">{project.outcome}</p></div></div></Container></section>
    <section className="bg-surface py-28 sm:py-36 lg:py-44"><Container><div className="flex items-end justify-between gap-6"><div><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Related projects</p><h2 className="mt-5 font-display text-4xl tracking-[-0.04em] sm:text-5xl">Continue exploring.</h2></div><Link to="/projects" className="hidden min-h-11 items-center text-[0.65rem] font-semibold tracking-[0.16em] uppercase sm:flex">All projects <ArrowRight className="ml-3 size-4" /></Link></div><div className="mt-12 grid gap-7 md:grid-cols-3">{related.map((item) => <Link key={item.id} to={`/projects/${item.slug}`} className="group"><div className="aspect-[4/5] overflow-hidden"><motion.img whileHover={{ scale: 1.05 }} transition={{ duration: 0.7 }} src={item.coverImage} alt="" className="h-full w-full object-cover" /></div><h3 className="mt-4 font-display text-3xl tracking-[-0.035em]">{item.title}</h3><p className="mt-2 text-[0.62rem] font-medium tracking-[0.14em] text-muted uppercase">{item.location}</p></Link>)}</div></Container></section>
    <section className="bg-ink py-28 text-inverse sm:py-36 lg:py-44"><Container className="text-center"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-white/55 uppercase">Begin a conversation</p><h2 className="mx-auto mt-6 max-w-3xl font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl">Let’s make a place that feels entirely your own.</h2><motion.div initial="rest" whileHover="hover" className="mt-10 inline-flex"><Link to="/contact" className="flex min-h-14 min-w-64 items-center justify-between border border-white px-6 text-[0.66rem] font-semibold tracking-[0.16em] uppercase">Book a consultation <motion.span variants={{ rest: { x: 0 }, hover: { x: 5 } }}><ArrowRight className="size-4" /></motion.span></Link></motion.div></Container></section>
  </>
}
