import { ChevronDown } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { useState } from 'react'

const items = [['How long do projects take?', 'The scope sets the pace. A furnished apartment may take four to six months; a full residence or villa typically takes nine to eighteen months.'], ['What cities do you serve?', 'We work from London across the UK, Europe, and selected international locations.'], ['How does the consultation work?', 'We begin with a focused conversation about your space, ambitions, timeline, and investment level, then recommend the most useful next step.'], ['Can you work remotely?', 'Yes. Our process is designed to work seamlessly across locations, with clear milestones and regular site visits when needed.'], ['What is your pricing model?', 'Every commission is tailored. We provide a clear scope and fee proposal after the initial conversation.'], ['Do you offer turnkey execution?', 'Yes. We can lead the process from concept through procurement, installation, and final styling.']]

export function Faq() {
  const [open, setOpen] = useState(0)
  return <section className="bg-canvas py-28 sm:py-36 lg:py-48"><div className="mx-auto grid max-w-[1440px] gap-14 px-6 md:grid-cols-12 md:px-10 lg:px-14"><div className="md:col-span-4"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Questions, answered</p><h2 className="mt-6 font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl">The practical things.</h2></div><div className="md:col-span-7 md:col-start-6">{items.map(([question, answer], index) => <div key={question} className="border-t border-line"><button type="button" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index} className="flex min-h-18 w-full items-center justify-between gap-6 py-5 text-left"><span className="font-display text-2xl tracking-[-0.025em] sm:text-3xl">{question}</span><motion.span animate={{ rotate: open === index ? 180 : 0 }}><ChevronDown className="size-5 text-accent" /></motion.span></button><AnimatePresence initial={false}>{open === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.35 }} className="overflow-hidden"><p className="max-w-xl pb-7 text-sm leading-7 text-muted">{answer}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>
}
