import { motion } from 'motion/react'

import studioMaterials from '../../assets/studio-materials.png'
import { Container } from '../ui/container'

const materials = ['Wood', 'Stone', 'Marble', 'Brass', 'Natural fabrics']
const principles = ['Timeless', 'Functional', 'Elegant', 'Intentional']

export function StudioStory() {
  return (
    <>
      <section className="bg-surface py-28 sm:py-36 lg:py-48"><Container className="grid gap-12 md:grid-cols-12 md:items-end"><motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.8 }} className="md:col-span-8"><p className="mb-6 text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Studio story</p><h2 className="font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl md:text-7xl">We look for the enduring character beneath the obvious.</h2></motion.div><motion.p initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.75, delay: 0.1 }} className="max-w-sm text-sm leading-7 text-muted md:col-span-4 md:justify-self-end">Decor &amp; Design was founded on the belief that interiors should gather meaning with time. We work slowly enough to notice the grain, the changing light, and the quiet possibilities of a plan.</motion.p></Container></section>
      <section className="bg-canvas py-20 sm:py-28 lg:py-36"><div className="mx-auto max-w-[1728px] lg:grid lg:grid-cols-2"><motion.div initial={{ opacity: 0, scale: 1.02 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 1 }} className="aspect-[4/5] overflow-hidden lg:aspect-auto lg:min-h-[720px]"><img src={studioMaterials} alt="Sketches, textiles, and stone samples in the studio" className="h-full w-full object-cover" /></motion.div><div className="flex flex-col justify-center px-6 py-20 sm:px-10 lg:px-[clamp(3rem,8vw,10rem)]"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Craftsmanship</p><h2 className="mt-6 font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl">Made with the hand and held by the eye.</h2><p className="mt-8 max-w-lg text-sm leading-7 text-muted sm:text-base sm:leading-8">Our work is built in close conversation with cabinetmakers, stone specialists, metalworkers, and upholsterers. Their knowledge gives the finished rooms an honesty that cannot be drawn into a plan alone.</p></div></div></section>
      <section className="bg-surface py-28 sm:py-36 lg:py-48"><Container><div className="grid gap-8 md:grid-cols-12"><div className="md:col-span-5"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Materials we love</p><h2 className="mt-6 font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl">A palette that rewards a closer look.</h2></div><div className="md:col-span-6 md:col-start-7">{materials.map((material, index) => <motion.div key={material} initial={{ opacity: 0, x: 18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.65, delay: index * 0.06 }} className="flex items-center justify-between border-t border-line py-6"><span className="font-display text-3xl tracking-[-0.03em] sm:text-4xl">{material}</span><span className="text-[0.62rem] font-semibold tracking-[0.16em] text-muted uppercase">0{index + 1}</span></motion.div>)}</div></div></Container></section>
      <section className="bg-canvas py-28 sm:py-36 lg:py-48"><Container><div className="max-w-3xl"><p className="text-[0.65rem] font-semibold tracking-[0.2em] text-accent uppercase">Design principles</p><h2 className="mt-6 font-display text-5xl leading-[0.9] tracking-[-0.045em] sm:text-6xl md:text-7xl">The measure behind every decision.</h2></div><div className="mt-16 grid grid-cols-2 border-t border-line md:mt-24 md:grid-cols-4">{principles.map((principle, index) => <motion.div key={principle} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.65, delay: index * 0.07 }} className="border-b border-r border-line p-5 last:border-r-0 sm:p-8"><p className="text-[0.62rem] font-semibold tracking-[0.16em] text-accent uppercase">0{index + 1}</p><h3 className="mt-10 font-display text-3xl tracking-[-0.03em] sm:text-4xl">{principle}</h3></motion.div>)}</div></Container></section>
    </>
  )
}
